### ISSUE TITLE
Update RSVP page to display all others going for the event

### ISSUE THREAD

**Issue by probablyangg** [kernel-community/convo-app#236]
### requirements

- [x] Attendees able to View all others attending an event after marking yourself as going
- [x] Organizer sees all RSVPs and an ability to copy all emails (an option to send an email directly will come later)

---
### todo

- [x] the component is only visible if you are logged in
- [x] Click on the component to open a modal
- [x] Modal should display: all other rsvp names 
- [x] a close button
- [x] If organizer clicks on the component, the modal displays all emails and a button to copy all emails (comma separated)
